version: '3'
services:
  web:
    image: ${IMAGE_WEB_APP}:${BUILD_VERSION}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    environment:
      - SPRING_DATA_MONGODB_HOST=${SPRING_DATA_MONGODB_HOST}
      - APP_SERVER_PORT=${APP_SERVER_PORT}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
    depends_on:
      - mongo

  mongo:
    image: mongo:${MONGO_IMAGE_VERSION}
    ports:
      - ${MONGO_DB_PORT}:27017